# ----------------------------------------------------- 
# Monitor Setup
# name: "2560x1440"
# ----------------------------------------------------- 

monitor=eDP-1,2560x1600@165.0,0x0,1
#monitor=DP-11,2560x1440@60,auto-right,1
#monitor=DP-12,2560x1440@60,auto-right,1
monitor=,2560x1440@59.95,auto-right,1
