color0       #464B50
color8       #97A5AB
color1       #6C7892
color9       #6C7892
color2       #0087AD
color10      #0087AD
color3       #A5ACBD
color11      #A5ACBD
color4       #48BADB
color12      #48BADB
color5       #CBB5A8
color13      #CBB5A8
color6       #C0EAFB
color14      #C0EAFB
color7       #D7ECF5
color15      #D7ECF5