cursor #dee3e5
cursor_text_color #bfc8ca

foreground            #dee3e5
background            #101010
selection_foreground  #1c3439
selection_background  #b1cbd1
url_color             #82d3e3

# black
# color8   #262626
# color8 - auto complete preview
color8   #525252
color0   #262626

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #94D497
color10  #94D497

# yellow
color3   #bcc5eb
color11  #bcc5eb

# blue
/* color4  #8f8aac */
color4  #b1cbd1
color12 #b1cbd1

# magenta
color5   #82d3e3
color13  #82d3e3

# cyan
color6   #bcc5eb
color14  #bcc5eb

# white
color15  #dee3e5
color7   #dee3e5
