color0       #545354
color8       #A19D9A
color1       #8C62A2
color9       #8C62A2
color2       #788AA8
color10      #788AA8
color3       #9F908F
color11      #9F908F
color4       #BA92C3
color12      #BA92C3
color5       #B6B9CF
color13      #B6B9CF
color6       #DED3C9
color14      #DED3C9
color7       #E6E1DC
color15      #E6E1DC