cursor #e3e1e9
cursor_text_color #c6c5d0

foreground            #e3e1e9
background            #000000
selection_foreground  #2c2f42
selection_background  #c2c5dd
url_color             #b7c4ff

# black
color0   #0d0e13
color8   #5d5e6a

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #94D497
color10  #94D497

# yellow
color3   #e4bad9
color11  #e4bad9

# blue
color4  #7683b6
color12 #7683b6

# magenta
color5   #b7c4ff
color13  #b7c4ff

# cyan
color6   #6673ad
color14  #6673ad

# white
color7   #e3e1e9
color15  #e3e1e9
