# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile,^(Microsoft-edge)$
windowrule = tile,^(Brave-browser)$
windowrule = tile,^(Chromium)$
windowrule = float,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = float,^(qalculate-gtk)$
windowrulev2 = monitor 0,class:^(rambox)$

# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$

# Firewall OpenSnitch UI
windowrulev2 = float, class:(opensnitch_ui)
windowrulev2 = pin, class:(opensnitch_ui)
windowrulev2 = center, class:(opensnitch_ui)
windowrulev2 = size 1280 900, class:(opensnitch_ui)
